# Generated by Django 5.1.3 on 2024-11-09 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_line', models.IntegerField(default=-1, null=True)),
                ('time_stamp', models.DateTimeField(default=-1, null=True)),
                ('box_positions', models.CharField(choices=[('M', 'Middle'), ('B', 'Back')], default='MIDDLE', max_length=64)),
                ('bike_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('pram_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('wheel_chair_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Changeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_line', models.IntegerField(default=-1, null=True)),
                ('time_stamp', models.DateTimeField(default=-1, null=True)),
                ('to_line', models.IntegerField()),
                ('changeover_managed', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_line', models.IntegerField(default=-1, null=True)),
                ('time_stamp', models.DateTimeField(default=-1, null=True)),
                ('occupancy_rating', models.CharField(choices=[('VL', 'Very Low'), ('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('VH', 'Very High')], default='Medium', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_line', models.IntegerField(default=-1, null=True)),
                ('time_stamp', models.DateTimeField(default=-1, null=True)),
                ('on_time', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
