# Generated by Django 5.1.3 on 2024-11-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swifttransit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pramslot',
            name='basefeedback_ptr',
        ),
        migrations.DeleteModel(
            name='BikeSlot',
        ),
        migrations.DeleteModel(
            name='PramSlot',
        ),
    ]
